### ISSUE TITLE
Idea: Compile PDF using GitHub Actions

### ISSUE THREAD

**Issue by patrickm663** [dariotrinchero/cv#2]
Hi Dario

If you're interested, I ended up doing something similar (also based off AltaCV) and used GitHub Actions to compile the PDF on every successful commit to main. I send my PDF to S3 but that is personal preference. I faced some issues selecting the correct LaTeX action so hopefully this helps someone :)

I need to update mine some more re formatting issues but here's my repo: https://github.com/patrickm663/cv.

Please feel free to close if it's not relevant.

Regards
Patrick

**Comment by dariotrinchero** [comment]
Hey Patrick

That is a great suggestion - thanks!

I did consider it, only I suspected that it might have used too much of the free GitHub Actions compute time to get a LuaTeX installation up, etc. Since you mention it, it cannot be too expensive, so I'll definitely look into it.

**Comment by patrickm663** [comment]
Hey Dario

I've noticed the pipeline can take 1.5-2.5 mins to run, so very fair point to keep an eye on the free credits. As of now, I haven't been notified/warned by GitHub, but I suspect it might not be feasible if one has a number of repos using GitHub Actions.

**Comment by dariotrinchero** [comment]
I ended up implementing your idea in the end! Thanks a bunch! As, you can see, I opted to host the compiled PDF right here on GitHub as part of a continuously-updating Release. Then my website and stuff can just reference that file via its permalink. Even the README on this repo can include a nice image preview.

Great idea. Thanks again.

**Comment by patrickm663** [comment]
Thanks for the update! It comes our really nice as an image preview!

You're welcome, happy to have helped. Best of luck with your PhD.
